name: covid_19
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  intl: ^0.16.0
  google_fonts: ^0.3.9
  firebase_admob: ^0.9.1+1
  platform: ^2.2.1
  device_info: ^0.4.1+5
  http: ^0.12.0+4
  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/undraw/"

flutter_intl:
  enabled: true

